import { images } from "../content";
import { PageHero, QuoteCta, SiteFooter, SiteHeader } from "../site-components";

const buyers = [
  ["Government departments", "Departmental requirement lists across medical, office and general categories."], ["Municipal bodies", "Civic, sanitation, waste handling and public facility supplies."], ["Hospitals and clinics", "Pharmaceuticals, surgical items, dressings and hospital consumables."], ["Educational institutions", "School stationery, classroom material and institutional furniture."], ["Offices and organisations", "Stationery, printer consumables, housekeeping and utility items."], ["Retail and wholesale partners", "Bulk pharmaceutical and surgical supply for pharmacies and distributors."],
] as const;
const process = [["Share the requirement", "Send your item list, quantities and any specification by WhatsApp, email or phone."], ["We source and quote", "We check availability with the appropriate manufacturers, distributors and suppliers, then send pricing."], ["Confirm the order", "You confirm the items, quantities and delivery details, and we begin processing."], ["Dispatch and support", "Goods are dispatched and we stay reachable for follow up, repeat orders and clarifications."]] as const;

export default function AboutPage() {
  return <><SiteHeader active="about" /><main><PageHero eyebrow="Our Business" title="From healthcare to government procurement, dependable supply solutions across multiple categories" image={images.warehouse} />
    <section className="section-pad"><div className="shell editorial-grid"><div className="section-heading"><p className="eyebrow">Our Business</p><h2>A supplier built around the requirement list, not a single product line</h2></div><div className="long-copy"><p>Nishant Pharma has grown into a dependable name for pharmaceuticals, surgical instruments, hospital consumables and general medical supplies. We work with manufacturers and authorised distributors to keep genuine, quality checked products moving to our retail and institutional partners.</p><p>As buyers asked for more than medicines, the business widened. Today the same team also handles government and institutional procurement covering municipal products, cleaning and sanitation items, safety equipment, office and school supplies, electrical and utility products, furniture and mobility equipment.</p><ul className="check-list"><li>Wide range across medicines, surgical tools and disposables</li><li>Government, municipal and institutional categories under one supplier</li><li>Competitive wholesale pricing for retailers, clinics and bulk buyers</li><li>Fast order processing and dependable delivery</li><li>Proper storage and handling for sensitive stock</li><li>Single point of contact for mixed requirement lists</li></ul></div></div></section>
    <section className="section-pad section-soft"><div className="shell statement"><p>From healthcare to government procurement, we provide dependable supply solutions across multiple categories.</p><div>Our aim is simple. A buyer with a mixed requirement list should be able to send it to one supplier, receive one quotation and follow one order, instead of coordinating a separate vendor for every line.</div></div></section>
    <section className="section-pad"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">Who We Serve</p><h2>Requirements across six kinds of buyer</h2></div><p>The categories overlap more than people expect. A hospital needs stationery, a school needs cleaning supplies, and a municipal office needs both safety gear and first aid consumables. Supplying across categories is what lets us handle mixed lists.</p></div><div className="numbered-grid six">{buyers.map(([title, copy], i) => <article key={title}><span>{String(i + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section-pad section-dark"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow eyebrow-light">How We Work</p><h2>From requirement list to delivered order</h2></div></div><ol className="process-row">{process.map(([title, copy], i) => <li key={title}><span>{String(i + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>
    <QuoteCta title="Want to know whether we can supply a particular item?" copy="Send the item name or specification and we will confirm whether it is something we can source for you." />
  </main><SiteFooter /></>;
}
