import Link from "next/link";
import { images, whatsappFor, whyCards } from "./content";
import { ArrowIcon, CheckIcon, QuoteCta, SiteFooter, SiteHeader } from "./site-components";

const homeCategories = [
  ["Pharmaceuticals", "Medicines for hospitals, clinics, pharmacies and healthcare institutions.", ["Tablets", "Capsules", "Syrups", "Injectables", "Generic medicines", "Branded medicines", "Healthcare products"], images.pharma],
  ["Surgical & Medical Supplies", "Instruments, disposables and consumables for clinical and hospital use.", ["Surgical instruments", "Surgical disposables", "Gloves", "Masks", "Syringes", "Gauze", "Bandages", "OT consumables", "Hospital consumables"], images.surgical],
  ["Government & Institutional Supplies", "Broad procurement support for departments, institutions and public sector requirements.", ["General government procurement items", "Institutional supplies", "Public sector requirements", "Bulk procurement products"], images.garbageTruck],
  ["Cleaning & Sanitation", "Sanitation, hygiene and waste handling products for municipal and institutional use.", ["Dustbins", "Cleaning equipment", "Sanitation products", "Waste management products", "Hygiene products"], images.wasteIndoor],
  ["Safety & Security Supplies", "Personal protective equipment and site safety items for staff and field teams.", ["Safety equipment", "PPE", "Reflective jackets", "Helmets", "Safety accessories", "Emergency and safety products"], images.safety],
  ["Office & School Supplies", "Everyday consumables and record keeping material for offices, schools and institutions.", ["Stationery", "Office supplies", "School supplies", "Printers and accessories", "Files and registers", "General office consumables"], images.office],
] as const;

const buyers = [
  ["Government & municipal buyers", "Requirement lists covering medical, sanitation, safety, office and civic categories."],
  ["Hospitals, clinics & health centres", "Medicines, surgical instruments, dressings and everyday hospital consumables."],
  ["Schools, colleges & institutions", "Stationery, furniture, cleaning material and general institutional supplies."],
  ["Pharmacies, retailers & distributors", "Wholesale pharmaceutical and surgical supply with bulk pricing."],
] as const;

export default function Home() {
  return <><SiteHeader active="home" /><main>
    <section className="hero section-pad"><div className="shell hero-grid">
      <div className="hero-copy"><p className="eyebrow">Multi Category Supplier</p><h1>Government Supplies. Healthcare Supplies. Reliable Procurement.</h1><p className="hero-lead">A trusted supplier for pharmaceuticals, surgical products, medical equipment, government tenders, institutional supplies and a wide range of procurement requirements.</p><div className="actions"><Link className="button button-primary" href="/government-supplies">Government supplies <ArrowIcon /></Link><Link className="button button-secondary" href="/products">All product categories</Link></div><div className="trust-line"><span><CheckIcon /> One supplier</span><span><CheckIcon /> Multiple requirements</span><span><CheckIcon /> Bulk supply</span></div></div>
      <div className="hero-collage" aria-label="Government and institutional supply categories"><figure className="collage-main"><img src={images.erickshaw} alt="Electric rickshaws for municipal and utility use" /></figure><figure><img src={images.wasteIndoor} alt="Waste segregation and municipal supplies" /></figure><figure><img src={images.safety} alt="Industrial safety equipment and PPE" /></figure><figure><img src={images.lighting} alt="Solar street lighting and electrical supplies" /></figure><div className="collage-label">Government · Municipal · Safety · Utility</div></div>
    </div></section>
    <section className="section-pad"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">Who We Supply</p><h2>One reliable supplier for government, institutional, medical and general procurement</h2></div><p>Nishant Pharma began in pharmaceutical and surgical wholesale and now supplies across a much wider set of categories, so a single requirement list can be handled end to end.</p></div><div className="numbered-grid">{buyers.map(([title, copy], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section-pad section-soft"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">What We Supply</p><h2>Supply categories</h2></div><p>Ten broad categories covering healthcare, government, municipal and institutional requirements. Tap Enquire Now on any category to start a WhatsApp conversation.</p></div><div className="supply-grid">{homeCategories.map(([title, description, items, image]) => <article className="supply-card" key={title}><img src={image} alt={title} /><div><h3>{title}</h3><p>{description}</p><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><a href={whatsappFor(title)} target="_blank" rel="noreferrer">Enquire now <ArrowIcon /></a></div></article>)}</div><div className="center-action"><Link className="button button-primary" href="/products">View all ten categories <ArrowIcon /></Link></div></div></section>

    <section className="section-pad"><div className="shell govt-feature"><div><p className="eyebrow">Government Supplies</p><h2>Built for departmental and institutional requirement lists</h2><p>We supply government departments, municipal bodies, hospitals, schools and other organisations across medical, civic, safety, office and utility categories, quoted against the specification you share with us.</p><ul className="check-list"><li>Municipal and civic supplies</li><li>Waste management and dustbins</li><li>E-rickshaws, scooters and mobility products</li><li>Safety equipment and PPE</li><li>Office, school and institutional supplies</li><li>Electrical, utility and furniture items</li></ul><Link className="button button-primary" href="/government-supplies">View government capability <ArrowIcon /></Link></div><div className="government-photo-grid"><img src={images.garbageTruck} alt="Municipal garbage truck and waste bins" /><img src={images.erickshaw} alt="E-rickshaw mobility products" /><img src={images.lighting} alt="Solar street lighting and electrical utility products" /><img src={images.safety} alt="Safety equipment and PPE" /></div></div><div className="compact-four"><article><h3>Dustbins</h3><p>Indoor, outdoor and large wheeled dustbins in a range of capacities and materials.</p></article><article><h3>E-Rickshaws</h3><p>Battery operated three wheelers for passenger, loader and municipal utility use.</p></article><article><h3>Safety Equipment</h3><p>Helmets, reflective jackets, protective gear and site safety accessories.</p></article><article><h3>Electrical & Utility Products</h3><p>LED lighting, cables, fittings and general electrical maintenance items.</p></article></div></section>

    <section className="section-pad section-dark"><div className="shell gallery-preview"><div><p className="eyebrow eyebrow-light">Product Gallery</p><h2>A look at what we handle</h2><p>Photographs of our pharmaceutical and surgical stock, alongside illustrated references for the government, municipal, safety, office and electrical categories we supply.</p><Link className="button button-gold" href="/gallery">Open full gallery <ArrowIcon /></Link></div><div className="preview-images"><img src={images.safety} alt="Safety equipment and PPE" /><img src={images.garbageTruck} alt="Municipal garbage truck and waste supplies" /><img src={images.lighting} alt="Solar street lighting" /></div></div></section>

    <section className="section-pad"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">Why Us</p><h2>Why buyers work with us</h2></div></div><div className="numbered-grid">{whyCards.slice(0, 4).map(([title, copy], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="center-action"><Link className="button button-secondary" href="/why-us">See all reasons</Link></div></div></section>
    <QuoteCta title="Share your requirement list and we will quote against it" copy="Send us your item list, quantities and specification by WhatsApp or email. We respond with availability and pricing." />
  </main><SiteFooter /></>;
}
