import { governmentCategories, images, whatsappFor } from "../content";
import { ArrowIcon, PageHero, QuoteCta, SiteFooter, SiteHeader } from "../site-components";

const who = ["Government departments and offices", "Municipal and civic bodies", "Government hospitals and health centres", "Schools, colleges and educational institutions", "Public sector organisations and boards", "Institutional and commercial organisations"];
const reasons = [["Wide product range", "Healthcare, municipal, office, safety and general categories under one supplier."], ["Bulk supply capability", "Order quantities scaled for departmental and institutional requirement lists."], ["Reliable sourcing", "Products sourced through appropriate manufacturers, distributors and suppliers."], ["Quality focused procurement", "Product selection checked against the specification you share with us."], ["Competitive pricing", "Rates worked out for bulk and repeat institutional orders."], ["Timely order processing", "Quick response on quotations and clear communication on dispatch."], ["Institutional support", "Assistance with requirement lists, alternatives and item level clarifications."], ["Tender oriented supply", "Supply capability suited to tender and rate contract style requirement lists."], ["One stop procurement", "Multiple categories consolidated into a single point of contact."]] as const;
const process = [["Requirement received", "You send the requirement list, tender line items or specification by WhatsApp, email or phone."], ["Sourcing and rate working", "We check availability with the appropriate manufacturers, distributors and suppliers for each category."], ["Quotation shared", "You receive item level pricing along with any alternatives where a specific item is not available."], ["Supply and dispatch", "On confirmation the order is processed and dispatched, and we remain reachable for follow up."]] as const;

export default function GovernmentSuppliesPage() {
  return <><SiteHeader active="government" /><main><PageHero eyebrow="Government Supplies" title="Comprehensive Government & Institutional Supply Solutions" image={images.erickshaw} />
    <section className="section-pad"><div className="shell editorial-grid"><div className="section-heading"><p className="eyebrow">Supply Capability</p><h2>One supplier across the categories a department actually orders</h2></div><div className="long-copy"><p>Departmental and institutional purchase lists rarely stay inside one product family. A single list can move from medicines and dressings to dustbins, safety jackets, printer paper and LED fittings. We supply across those categories so the whole list can be quoted, ordered and followed through one supplier.</p><p>Our supply capability is suited to tender style and rate contract style requirement lists, where items are specified in advance and quantities are fixed. Share the list and we will work out sourcing and rates against it.</p><h3>Who We Supply</h3><ul className="check-list">{who.map(item => <li key={item}>{item}</li>)}</ul><div className="tender-note"><b>Government Tender Supply Capability</b><p>Supply against tender and institutional requirement lists, with item level clarification where a specification needs it.</p></div></div></div></section>
    <section className="section-pad section-soft"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">Supply Categories</p><h2>Sixteen government and institutional categories</h2></div><p>Each category opens a WhatsApp enquiry with the category name already written, so you can add your quantities and send it straight away.</p></div><div className="government-category-grid">{governmentCategories.map(([title, copy], i) => <article id={title.toLowerCase().replace(/&/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")} key={title}><span>{String(i + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p><a href={whatsappFor(title)} target="_blank" rel="noreferrer">Enquire <ArrowIcon /></a></article>)}</div></div></section>
    <section className="wide-photo"><img src={images.garbageTruck} alt="Municipal garbage truck and waste management products" /><img src={images.safety} alt="Government safety equipment and PPE" /><img src={images.wasteVehicle} alt="Municipal waste collection vehicle" /><img src={images.lighting} alt="Solar electrical and utility street lighting" /></section>
    <section className="section-pad"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">Why Government Departments Choose Us</p><h2>What we bring to institutional procurement</h2></div></div><div className="numbered-grid three">{reasons.map(([title, copy], i) => <article key={title}><span>{String(i + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section-pad section-dark"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow eyebrow-light">Order Process</p><h2>How a departmental order runs</h2></div><p>A straightforward sequence, so you always know which stage your requirement is at.</p></div><ol className="process-row">{process.map(([title, copy], i) => <li key={title}><span>{String(i + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>
    <QuoteCta title="Send your departmental or tender requirement list" copy="Share the item list, quantities and specification. We will come back with sourcing and rates." />
  </main><SiteFooter /></>;
}
